-- Commissioner Tools provider connection foundation.
--
-- This migration intentionally stores no OAuth access tokens, refresh tokens,
-- client secrets, or authorization codes. Credential storage is a separate
-- security boundary and must be reviewed before customer OAuth is persisted.

CREATE TABLE IF NOT EXISTS public.provider_connection (
    provider_connection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    provider_code text NOT NULL,
    external_account_id text,
    external_account_name text,
    status text NOT NULL DEFAULT 'pending',
    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now(),
    last_verified_at_utc timestamptz,
    disconnected_at_utc timestamptz,

    CONSTRAINT provider_connection_user_fk
        FOREIGN KEY (user_id)
        REFERENCES public.auth_user (user_id)
        ON DELETE CASCADE,

    CONSTRAINT provider_connection_provider_code_check
        CHECK (
            provider_code <> ''
            AND provider_code = lower(btrim(provider_code))
        ),

    CONSTRAINT provider_connection_status_check
        CHECK (
            status IN (
                'pending',
                'active',
                'error',
                'disconnected'
            )
        ),

    CONSTRAINT provider_connection_id_provider_unique
        UNIQUE (provider_connection_id, provider_code)
);

CREATE INDEX IF NOT EXISTS
    ix_provider_connection_user
ON public.provider_connection (user_id);

CREATE INDEX IF NOT EXISTS
    ix_provider_connection_user_provider
ON public.provider_connection (user_id, provider_code);

CREATE INDEX IF NOT EXISTS
    ix_provider_connection_status
ON public.provider_connection (status);

CREATE UNIQUE INDEX IF NOT EXISTS
    ux_provider_connection_active_external_account
ON public.provider_connection (
    user_id,
    provider_code,
    external_account_id
)
WHERE external_account_id IS NOT NULL
  AND status <> 'disconnected';


CREATE TABLE IF NOT EXISTS public.provider_league_binding (
    provider_league_binding_id bigint
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    provider_connection_id bigint NOT NULL,
    provider_code text NOT NULL,

    league_key text NOT NULL,
    season_year integer NOT NULL,

    provider_league_id text NOT NULL,
    provider_game_id text,
    provider_league_name text,

    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now(),
    last_synced_at_utc timestamptz,

    CONSTRAINT provider_league_binding_connection_fk
        FOREIGN KEY (
            provider_connection_id,
            provider_code
        )
        REFERENCES public.provider_connection (
            provider_connection_id,
            provider_code
        )
        ON DELETE CASCADE,

    CONSTRAINT provider_league_binding_profile_fk
        FOREIGN KEY (
            league_key,
            season_year
        )
        REFERENCES public.league_profile (
            league_key,
            season_year
        )
        ON DELETE CASCADE,

    CONSTRAINT provider_league_binding_provider_code_check
        CHECK (
            provider_code <> ''
            AND provider_code = lower(btrim(provider_code))
        ),

    CONSTRAINT provider_league_binding_league_key_check
        CHECK (btrim(league_key) <> ''),

    CONSTRAINT provider_league_binding_season_year_check
        CHECK (season_year > 0),

    CONSTRAINT provider_league_binding_provider_league_id_check
        CHECK (btrim(provider_league_id) <> ''),

    CONSTRAINT provider_league_binding_league_provider_unique
        UNIQUE (
            league_key,
            season_year,
            provider_code
        ),

    CONSTRAINT provider_league_binding_connection_league_unique
        UNIQUE (
            provider_connection_id,
            provider_league_id
        )
);

CREATE INDEX IF NOT EXISTS
    ix_provider_league_binding_connection
ON public.provider_league_binding (provider_connection_id);

CREATE INDEX IF NOT EXISTS
    ix_provider_league_binding_commercial_league
ON public.provider_league_binding (league_key, season_year);
