-- MLF Relational Migration - 001
-- Dedicated MLF draft-domain foundation.
--
-- IMPORTANT:
--   * This file belongs to the MLF relational rebuild.
--   * Do not apply to production yet.
--   * Existing public.* MLF data remains untouched.
--   * Contracts, PT, QO, auth, clock, and atomic execution are
--     intentionally handled by later migrations.
--
-- Architectural source:
--   Adapt generic draft concepts proven in NFFL while preserving
--   MLF-specific policy boundaries.

BEGIN;

CREATE SCHEMA IF NOT EXISTS mlf;

CREATE TABLE mlf.schema_migration (
    migration_version text PRIMARY KEY,
    description text NOT NULL,
    applied_at_utc timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE mlf.team (
    league_key text NOT NULL,
    season_year integer NOT NULL,
    team_key text NOT NULL,
    team_name text NOT NULL,
    owner_name text,
    owner_guid text,
    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT team_pkey
        PRIMARY KEY (
            league_key,
            season_year,
            team_key
        ),

    CONSTRAINT team_season_year_ck
        CHECK (
            season_year >= 2000
            AND season_year <= 2100
        ),

    CONSTRAINT team_key_not_blank_ck
        CHECK (btrim(team_key) <> ''),

    CONSTRAINT team_name_not_blank_ck
        CHECK (btrim(team_name) <> '')
);

CREATE TABLE mlf.draft (
    draft_key text PRIMARY KEY,
    league_key text NOT NULL,
    season_year integer NOT NULL,
    draft_label text NOT NULL,

    manager_count integer NOT NULL,
    rounds_total integer NOT NULL,

    -- MLF 2026 canonical:
    -- QO rights occupy rounds 1-5.
    qo_rounds integer NOT NULL DEFAULT 5,
    first_standard_round integer NOT NULL DEFAULT 6,

    draft_order_mode text NOT NULL DEFAULT 'straight',
    status text NOT NULL DEFAULT 'setup',

    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT draft_season_year_ck
        CHECK (
            season_year >= 2000
            AND season_year <= 2100
        ),

    CONSTRAINT draft_manager_count_ck
        CHECK (manager_count > 0),

    CONSTRAINT draft_rounds_total_ck
        CHECK (rounds_total > 0),

    CONSTRAINT draft_qo_rounds_ck
        CHECK (
            qo_rounds >= 0
            AND qo_rounds < rounds_total
        ),

    CONSTRAINT draft_first_standard_round_ck
        CHECK (
            first_standard_round = qo_rounds + 1
            AND first_standard_round <= rounds_total
        ),

    CONSTRAINT draft_order_mode_ck
        CHECK (
            draft_order_mode IN (
                'straight',
                'snake'
            )
        ),

    CONSTRAINT draft_key_not_blank_ck
        CHECK (btrim(draft_key) <> ''),

    CONSTRAINT draft_label_not_blank_ck
        CHECK (btrim(draft_label) <> '')
);

CREATE TABLE mlf.draft_pick (
    draft_key text NOT NULL,
    pick_id text NOT NULL,

    round_number integer NOT NULL,
    slot_number integer NOT NULL,
    round_label text NOT NULL,

    -- QO means a slot in rounds 1-5.
    -- STANDARD means a slot in rounds 6+.
    -- This describes the slot, not the eventual selection action.
    pick_type text NOT NULL,

    -- Column identity never moves when a pick is traded.
    column_team_key text NOT NULL,

    -- Current ownership may move independently through trades.
    current_owner_team_key text NOT NULL,

    traded_flag boolean NOT NULL DEFAULT false,
    ownership_note text,

    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT draft_pick_pkey
        PRIMARY KEY (
            draft_key,
            pick_id
        ),

    CONSTRAINT draft_pick_draft_fk
        FOREIGN KEY (draft_key)
        REFERENCES mlf.draft (draft_key)
        ON DELETE CASCADE,

    CONSTRAINT draft_pick_slot_uq
        UNIQUE (
            draft_key,
            round_number,
            slot_number
        ),

    CONSTRAINT draft_pick_round_number_ck
        CHECK (round_number > 0),

    CONSTRAINT draft_pick_slot_number_ck
        CHECK (slot_number > 0),

    CONSTRAINT draft_pick_type_ck
        CHECK (
            pick_type IN (
                'QO',
                'STANDARD'
            )
        ),

    CONSTRAINT draft_pick_id_not_blank_ck
        CHECK (btrim(pick_id) <> ''),

    CONSTRAINT draft_pick_column_team_not_blank_ck
        CHECK (btrim(column_team_key) <> ''),

    CONSTRAINT draft_pick_owner_team_not_blank_ck
        CHECK (btrim(current_owner_team_key) <> '')
);

CREATE TABLE mlf.draft_pick_trade (
    trade_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    draft_key text NOT NULL,
    pick_id text NOT NULL,

    from_team_key text NOT NULL,
    to_team_key text NOT NULL,

    trade_date date,
    note text,

    created_at_utc timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT draft_pick_trade_pick_fk
        FOREIGN KEY (
            draft_key,
            pick_id
        )
        REFERENCES mlf.draft_pick (
            draft_key,
            pick_id
        )
        ON DELETE CASCADE,

    CONSTRAINT draft_pick_trade_distinct_teams_ck
        CHECK (from_team_key <> to_team_key),

    CONSTRAINT draft_pick_trade_from_team_not_blank_ck
        CHECK (btrim(from_team_key) <> ''),

    CONSTRAINT draft_pick_trade_to_team_not_blank_ck
        CHECK (btrim(to_team_key) <> '')
);

CREATE TABLE mlf.draft_selection (
    draft_key text NOT NULL,
    pick_id text NOT NULL,

    selecting_team_key text NOT NULL,
    yahoo_player_key text NOT NULL,

    -- Intentionally unconstrained in migration 001.
    --
    -- MLF must define its own real-pick state machine rather than
    -- inheriting NFFL's football-specific pick-kind constraint.
    pick_kind text NOT NULL,

    selected_at_utc timestamptz NOT NULL DEFAULT now(),
    selected_by text,
    note text,

    CONSTRAINT draft_selection_pkey
        PRIMARY KEY (
            draft_key,
            pick_id
        ),

    CONSTRAINT draft_selection_pick_fk
        FOREIGN KEY (
            draft_key,
            pick_id
        )
        REFERENCES mlf.draft_pick (
            draft_key,
            pick_id
        )
        ON DELETE CASCADE,

    CONSTRAINT draft_selection_player_uq
        UNIQUE (
            draft_key,
            yahoo_player_key
        ),

    CONSTRAINT draft_selection_team_not_blank_ck
        CHECK (btrim(selecting_team_key) <> ''),

    CONSTRAINT draft_selection_player_not_blank_ck
        CHECK (btrim(yahoo_player_key) <> ''),

    CONSTRAINT draft_selection_kind_not_blank_ck
        CHECK (btrim(pick_kind) <> '')
);

CREATE INDEX ix_mlf_draft_league_season
    ON mlf.draft (
        league_key,
        season_year
    );

CREATE INDEX ix_mlf_draft_pick_owner
    ON mlf.draft_pick (
        draft_key,
        current_owner_team_key
    );

CREATE INDEX ix_mlf_draft_pick_column
    ON mlf.draft_pick (
        draft_key,
        column_team_key
    );

CREATE INDEX ix_mlf_draft_selection_team
    ON mlf.draft_selection (
        draft_key,
        selecting_team_key
    );

INSERT INTO mlf.schema_migration (
    migration_version,
    description
)
VALUES (
    '001',
    'Dedicated MLF draft-domain foundation'
);

COMMIT;